### ISSUE TITLE
Packages to get after a fresh install

### ISSUE THREAD

**Issue by MadLittleMods** [MadLittleMods/linux-notes#5]
See https://github.com/MadLittleMods/linux-notes/issues/4 to make sure you're able to search for packages in the AUR (Arch User Repository).

See https://github.com/MadLittleMods/linux-notes/issues/48 for how to lock/pin dependencies that are coming from unofficial repositories like AUR.

### Installing packages

```
pamac install google-chrome
```

### TODO

 - [x] `barrier`
 - [x] ~~`sublime-text-4`~~ Use [official source and instructions](https://www.sublimetext.com/docs/linux_repositories.html#pacman)
 - [x] `google-chrome`
 - [x] `visual-studio-code-bin` (to get the non-OSS version which has settings sync, extensions, etc)
    - https://wiki.archlinux.org/title/Visual_Studio_Code
 - [x] `steam`
 - [x] `slack-desktop` (also needs `patch`)
 - [x] `discord`
 - [ ] ~~Piper (for mouse sensitivity/acceleration)~~
    - See https://github.com/MadLittleMods/linux-notes/issues/1
 - [ ] Screenshot tool
    - See https://github.com/MadLittleMods/linux-notes/issues/3

More developer related:

 - [x] Docker
    - See https://github.com/MadLittleMods/linux-notes/issues/28
 - [x] Postgres
     - See https://github.com/MadLittleMods/linux-notes/issues/27
